//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dieta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DD_Beneficiarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DD_Beneficiarios()
        {
            this.DD_Desembolso = new HashSet<DD_Desembolso>();
        }
    
        public int ID { get; set; }
        public string CODIGO { get; set; }
        public string NOMBRE { get; set; }
        public int ASIGNATURASID { get; set; }
        public int SOLICITUDESID { get; set; }
        public Nullable<int> DESAYUNO { get; set; }
        public Nullable<int> ALMUERZO { get; set; }
        public Nullable<int> CENA { get; set; }
        public Nullable<int> HOSPEDAJE { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
    
        public virtual DD_GrupoOcupacional DD_GrupoOcupacional { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DD_Desembolso> DD_Desembolso { get; set; }
        public virtual DD_Solicitudes DD_Solicitudes { get; set; }
    }
}
