//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dieta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DD_Bitacora
    {
        public int ID { get; set; }
        public string USERNAME { get; set; }
        public string EVENTO { get; set; }
        public System.DateTime DATE { get; set; }
    }
}
