//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dieta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DD_Cantidades
    {
        public int ID { get; set; }
        public int SOLICITUDESID { get; set; }
        public Nullable<int> DESAYUNO { get; set; }
        public Nullable<int> ALMUERZO { get; set; }
        public Nullable<int> CENA { get; set; }
        public Nullable<int> HOSPEDAJE { get; set; }
    
        public virtual DD_Solicitudes DD_Solicitudes { get; set; }
    }
}
