//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dieta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DD_Desembolso
    {
        public int ID { get; set; }
        public string CODIGO { get; set; }
        public int BENEFICIARIOID { get; set; }
        public string CODIGO_BENEFICIARIO { get; set; }
        public Nullable<int> MONTO { get; set; }
        public System.DateTime FECHA { get; set; }
        public string CONCEPTO { get; set; }
        public string AREA { get; set; }
        public string METODO_PAGO { get; set; }
    
        public virtual DD_Beneficiarios DD_Beneficiarios { get; set; }
    }
}
