//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dieta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISTANCIA
    {
        public int ID { get; set; }
        public int SOLICITUD { get; set; }
        public string DESDE { get; set; }
        public string HASTA { get; set; }
        public decimal KM { get; set; }
    
        public virtual DD_Solicitudes DD_Solicitudes { get; set; }
    }
}
