//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dieta.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProcesosDAEntities : DbContext
    {
        public ProcesosDAEntities()
            : base("name=ProcesosDAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PERFILE> PERFILES { get; set; }
        public virtual DbSet<USUARIO> USUARIOS { get; set; }
        public virtual DbSet<COSTO> COSTOes { get; set; }
        public virtual DbSet<DD_Solicitudes> DD_Solicitudes { get; set; }
        public virtual DbSet<DISTANCIA> DISTANCIAs { get; set; }
        public virtual DbSet<DD_Beneficiarios> DD_Beneficiarios { get; set; }
        public virtual DbSet<DD_Cantidades> DD_Cantidades { get; set; }
        public virtual DbSet<DD_Desembolso> DD_Desembolso { get; set; }
        public virtual DbSet<DD_GrupoOcupacional> DD_GrupoOcupacional { get; set; }
        public virtual DbSet<DD_Bitacora> DD_Bitacora { get; set; }
    }
}
