
CREATE TABLE [dbo].[DD_Solicitudes](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [varchar](150) NOT NULL,
	[FECHA] [date] NOT NULL,
	[CARGO] [varchar](100) NOT NULL,
	[DEPENDENCIA] [varchar](100) NOT NULL,
	[MOTIVO] [varchar](1000) NOT NULL,
	[F_ENTRADA] [datetime] NOT NULL,
	[F_SALIDA] [datetime] NOT NULL,
	[TIPO] [char](10) NOT NULL,
	[Combustible] [decimal](13, 2) NULL,
 CONSTRAINT [PK_SOLICITUDES] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE 

CREATE TABLE [dbo].[DD_GrupoOcupacional](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [varchar](50) NOT NULL,
	[DESAYUNO] [int] NOT NULL,
	[ALMUERZO] [int] NOT NULL,
	[CENA] [int] NOT NULL,
	[HOSPEDAJE] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[DD_Desembolso](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CODIGO] [varchar](10) NULL,
	[BENEFICIARIOID] [int] NOT NULL,
	[CODIGO_BENEFICIARIO] [varchar](10) NULL,
	[MONTO] [int] NULL,
	[FECHA] [date] NOT NULL,
	[CONCEPTO] [varchar](1000) NOT NULL,
	[AREA] [varchar](50) NOT NULL,
	[METODO_PAGO] [char](14) NOT NULL,
 CONSTRAINT [PK_REEMBOLSO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[DD_Desembolso]  WITH CHECK ADD  CONSTRAINT [FK_REEMBOLSO] FOREIGN KEY([BENEFICIARIOID])
REFERENCES [dbo].[DD_Beneficiarios] ([ID])
GO

ALTER TABLE [dbo].[DD_Desembolso] CHECK CONSTRAINT [FK_REEMBOLSO]
GO

ALTER TABLE [dbo].[DD_Desembolso]  WITH CHECK ADD CHECK  (([METODO_PAGO]='TRANSFERENCIA' OR [METODO_PAGO]='DATA' OR [METODO_PAGO]='CHEQUE'))
GO

CREATE TABLE [dbo].[DD_Cantidades](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[SOLICITUDESID] [int] NOT NULL,
	[DESAYUNO] [int] NULL,
	[ALMUERZO] [int] NULL,
	[CENA] [int] NULL,
	[HOSPEDAJE] [int] NULL,
 CONSTRAINT [PK_CANTIDADES] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[DD_Cantidades]  WITH CHECK ADD  CONSTRAINT [FK_SOLICITUDES] FOREIGN KEY([SOLICITUDESID])
REFERENCES [dbo].[DD_Solicitudes] ([ID])
GO

ALTER TABLE [dbo].[DD_Cantidades] CHECK CONSTRAINT [FK_SOLICITUDES]
GO

CREATE TABLE [dbo].[DD_Beneficiarios](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CODIGO] [varchar](10) NOT NULL,
	[NOMBRE] [varchar](50) NOT NULL,
	[ASIGNATURASID] [int] NOT NULL,
	[SOLICITUDESID] [int] NOT NULL,
	[DESAYUNO] [int] NULL,
	[ALMUERZO] [int] NULL,
	[CENA] [int] NULL,
	[HOSPEDAJE] [int] NULL,
	[TOTAL] [decimal](13, 2) NULL,
 CONSTRAINT [PK_BENEFICIARIO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[DD_Beneficiarios]  WITH CHECK ADD  CONSTRAINT [FK_ASIGNATURAS] FOREIGN KEY([ASIGNATURASID])
REFERENCES [dbo].[DD_GrupoOcupacional] ([ID])
GO

ALTER TABLE [dbo].[DD_Beneficiarios] CHECK CONSTRAINT [FK_ASIGNATURAS]
GO

ALTER TABLE [dbo].[DD_Beneficiarios]  WITH CHECK ADD  CONSTRAINT [FK_SOLICITUDES2] FOREIGN KEY([SOLICITUDESID])
REFERENCES [dbo].[DD_Solicitudes] ([ID])
GO

ALTER TABLE [dbo].[DD_Beneficiarios] CHECK CONSTRAINT [FK_SOLICITUDES2]
GO

CREATE TABLE DD_Bitacora(
ID INT NOT NULL CONSTRAINT PK_BITACORA PRIMARY KEY IDENTITY(1,1),
USERNAME VARCHAR(100) NOT NULL,
EVENTO VARCHAR(1000) NOT NULL,
DATE DATETIME NOT NULL
);

CREATE TABLE [dbo].[COSTO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[SOLICITUD] [int] NOT NULL,
	[COSTO] [decimal](13, 2) NOT NULL,
 CONSTRAINT [PK_COSTO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[COSTO]  WITH CHECK ADD  CONSTRAINT [FK_COSTO] FOREIGN KEY([SOLICITUD])
REFERENCES [dbo].[DD_Solicitudes] ([ID])
GO

ALTER TABLE [dbo].[COSTO] CHECK CONSTRAINT [FK_COSTO]
GO

CREATE TABLE [dbo].[DISTANCIA](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[SOLICITUD] [int] NOT NULL,
	[DESDE] [varchar](100) NOT NULL,
	[HASTA] [varchar](100) NOT NULL,
	[KM] [decimal](13, 2) NOT NULL,
 CONSTRAINT [PK_DISTANCIA] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[DISTANCIA]  WITH CHECK ADD  CONSTRAINT [FK_DISTANCIA] FOREIGN KEY([SOLICITUD])
REFERENCES [dbo].[DD_Solicitudes] ([ID])
GO

ALTER TABLE [dbo].[DISTANCIA] CHECK CONSTRAINT [FK_DISTANCIA]
GO

CREATE TABLE [dbo].[PERFILES](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[PERFIL] [varchar](100) NULL,
 CONSTRAINT [PK_PERFIL] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[USUARIOS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[USUARIO] [varchar](100) NOT NULL,
	[PASSWORD] [varchar](100) NOT NULL,
	[PERFIL] [int] NOT NULL,
 CONSTRAINT [PK_USUARIOS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[USUARIOS]  WITH CHECK ADD  CONSTRAINT [FK_USUARIOS] FOREIGN KEY([PERFIL])
REFERENCES [dbo].[PERFILES] ([ID])
GO

ALTER TABLE [dbo].[USUARIOS] CHECK CONSTRAINT [FK_USUARIOS]
GO

CREATE PROC [dbo].[CAL_COMBUSTIBLE]
  @ID INT
  AS

  UPDATE S 
  SET S.COMBUSTIBLE = (D.KM * C.COSTO)
  FROM DD_Solicitudes S INNER JOIN DISTANCIA D 
  ON S.ID = D.SOLICITUD INNER JOIN COSTO C ON C.SOLICITUD = S.ID WHERE S.ID = @ID

GO

CREATE PROC [dbo].[PROC_MULTIPLICAR] @IDPARAMETRO INT 
AS

  UPDATE B 
  SET B.DESAYUNO = A.DESAYUNO * C.DESAYUNO, B.ALMUERZO = A.ALMUERZO * C.ALMUERZO , B.CENA = A.CENA * C.CENA , B.HOSPEDAJE = A.HOSPEDAJE * C.HOSPEDAJE
  FROM DD_Beneficiarios B INNER JOIN DD_Solicitudes S
  ON S.ID = B.SOLICITUDESID INNER JOIN DD_Cantidades C ON S.ID = C.SOLICITUDESID  
  INNER JOIN DD_GrupoOcupacional A ON B.ASIGNATURASID = A.ID WHERE B.ID = @IDPARAMETRO;

  UPDATE B 
  SET B.TOTAL = (B.DESAYUNO+B.ALMUERZO+B.CENA+B.HOSPEDAJE)
  FROM DD_Beneficiarios B INNER JOIN DD_Solicitudes S 
  ON S.ID = B.SOLICITUDESID INNER JOIN DD_Cantidades C ON S.ID = C.SOLICITUDESID  
  INNER JOIN DD_GrupoOcupacional A ON B.ASIGNATURASID = A.ID WHERE B.ID = @IDPARAMETRO

  /*UPDATE B
  SET B.SUBTOTAL = (B.TOTAL+B.COMBUSTIBLE)
  FROM BENEFICIARIO B INNER JOIN SOLICITUDES S 
  ON S.ID = B.SOLICITUDESID INNER JOIN CANTIDADES C ON S.ID = C.SOLICITUDESID  
  INNER JOIN ASIGNATURAS A ON B.ASIGNATURASID = A.ID WHERE B.ID = @IDPARAMETRO*/
GO

CREATE TRIGGER TGG_BENEFICIARIO ON DD_BENEFICIARIOS
AFTER INSERT
AS

DECLARE @IDASIGNATURAS INT
DECLARE @ID INT
DECLARE @DESAYUNO INT
DECLARE @ALMUERZO INT
DECLARE @CENA INT
DECLARE @HOSPEDAJE INT

SELECT @IDASIGNATURAS = ASIGNATURASID, @ID = ID FROM INSERTED

SELECT @DESAYUNO = A.DESAYUNO, @ALMUERZO = A.ALMUERZO, @CENA = A.CENA, @HOSPEDAJE = A.HOSPEDAJE FROM 
DD_GrupoOcupacional A INNER JOIN DD_Beneficiarios B ON A.ID = B.ASIGNATURASID WHERE A.ID = @IDASIGNATURAS;

UPDATE DD_BENEFICIARIOS SET DESAYUNO = @DESAYUNO, ALMUERZO = @ALMUERZO, CENA = @CENA, HOSPEDAJE = @HOSPEDAJE, TOTAL = (@DESAYUNO + @ALMUERZO + @CENA + @HOSPEDAJE) WHERE ID = @ID;
GO

SELECT * FROM DD_Beneficiarios

CREATE PROC REPORT(@PARAMETRO INT)
AS

SELECT B.NOMBRE, A.NOMBRE, S.NOMBRE, B.DESAYUNO, B.ALMUERZO, B.CENA, B.HOSPEDAJE, C.DESAYUNO, C.ALMUERZO, C.CENA, C.HOSPEDAJE 
FROM DD_Beneficiarios B INNER JOIN DD_Solicitudes S ON B.SOLICITUDESID = S.ID INNER JOIN DD_GrupoOcupacional A ON B.ASIGNATURASID = A.ID
INNER JOIN DD_Cantidades C ON S.ID = C.SOLICITUDESID WHERE S.ID = @PARAMETRO

GO

EXEC REPORT 2

